---
- hosts: webserver
  tasks:
  - name: Parando Serviço
    systemd:
      name: apache2
      state: stopped 
      enabled: no
    ignore_errors: yes

  - name: Remove Packages APACHE
    apt: 
      name: apache2* 
      purge: yes
      state: absent
  
  - name: Autoremove
    apt:
      autoremove: yes
      purge: yes
  
  - name: Clean Folders and Files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/apache2
      - /var/www/html/index.html
...
