---
#### ---- Configurações Gerais ---- ####

- name: Alterações no arquivo /etc/profile
  lineinfile: dest=/etc/profile line={{ item }}
  with_items:
    - '#### ---- Linhas Adicionais ---- ####'
    - '### --- Variaveis e Alias Customizados --- ###'
    - 'export EDITOR=vim'
    - 'export HISTTIMEFORMAT="%d/%m/%Y - %H:%M:%S - "'
    - 'export HISTSIZE="5000"'
    - 'export HISTFILESIZE="5000"'
    - 'alias ls="ls --color"'
    - 'alias grep="grep -i --color"'

- name: Recarregando o /etc/profile
  shell: source /etc/profile
  #args:
  #  executable: /bin/bash
  
- name: Desabilitando o SELINUX de forma permanente
  replace: 
    dest: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    replace: 'SELINUX=disable'
  when: ansible_distribution_file_variety == 'RedHat'

#- name: Desabilitando o SELINUX de forma temporaria
#  shell: setenforce 0
#  when: ansible_distribution_file_variety == 'RedHat'

###############################################
### --- Manager Packages and Upgrade OS --- ###
###############################################

###############################################
###############################################
########### CENTOS/REDHAT #####################
###############################################
###############################################
#
#Install Repository EPEL-RELEASE
- name: Install Epel-release repository
  yum: name=epel-release state=latest
  when: ansible_distribution_file_variety == 'RedHat'

- name: Install Packages CentOS/RedHat
  yum: name={{ common_packages_redhat }} state=latest
#  Posso usar uma variavel aqui ou fazer a lista em default/main.yml
#  vars:
#    common_packages_redhat:
#    - vim
#    - tree
  when: ansible_distribution_file_variety == 'RedHat'

- name: Uninstall Packages CentOS/RedHat
  yum: name= {{ item  }} state=absent
  with_items:
    - postfix
    - firewalld
  when: ansible_distribution_file_variety == 'RedHat'

#Update Red Hat Distros
- name: Update Red Hat Distros
  yum: name=* state=latest security=yes update_cache=yes
  when: ansible_distribution_file_variety == 'RedHat'

###############################################
###############################################
###########  DEBIAN/UBUNTU ####################
###############################################
###############################################

#Update Debian Distro
- name: Update Debian/Ubuntu Distros
  apt: update_cache=yes upgrade=yes
  when: ansible_distribution_file_variety == 'Debian'

#Upgrade the Distro
- name: Upgrade Debian/Ubuntu Distros
  apt: upgrade=dist
  when: ansible_distribution_file_variety == 'Debian'

- name: Install Packages Debian/Ubuntu
  yum: name={{ common_packages_debian }} state=latest update_cache=yes
  when: ansible_distribution_file_variety == 'Debian'
