---
#### ---- Configurações Gerais ---- ####

- name: Alterações no arquivo /etc/profile
  lineinfile: dest=/etc/profile line={{ item }}
  with_items:
    - '#### ---- Linhas Adicionais ---- ####'
    - '### --- Variaveis e Alias Customizados --- ###'
    - 'export EDITOR=vim'
    - 'export HISTTIMEFORMAT="%d/%m/%Y - %H:%M:%S - "'
    - 'export HISTSIZE="5000"'
    - 'export HISTFILESIZE="5000"'
    - 'alias ls="ls --color"'
    - 'alias grep="grep -i --color"'

- name: Recarregando o /etc/profile
  shell: source /etc/profile
  #args:
  #  executable: /bin/bash
  
- name: Desabilitando o SELINUX de forma permanente
  replace: 
    dest: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    replace: 'SELINUX=disable'
  when: ansible_distribution_file_variety == 'RedHat'

#- name: Desabilitando o SELINUX de forma temporaria
#  shell: setenforce 0
#  when: ansible_distribution_file_variety == 'RedHat'


